### ISSUE TITLE
Shutdown application correctly

### ISSUE THREAD

**Issue by SirYwell** [PSNRigner/discord-rpc-java#5]
Hey, when closing your example apps, the game state stays the same. I didn't figured out until now how to remove the rich presence state. Should it automatically change?

**Comment by PSNRigner** [comment]
How are you launching the example ? If from an IDE, that's because of how Discord works (more info here :  https://github.com/discordapp/discord-rpc/issues/13 )

**Comment by SirYwell** [comment]
Okay, so that's the problem. Thanks for your explanation.
